Repository epam/edp-headlamp, pull requests merged in 2024-08, with the labels that each got.

#318 feat: Add clean env behaviour
  src/constants/pipelineTypes.ts
  src/k8s/groups/EDP/Stage/types.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.ts
  src/k8s/groups/Tekton/TriggerTemplate/hooks/useCleanTriggerTemplateListQuery.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/pages/pipelines/components/PipelineRunList/index.tsx
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
  src/pages/stage-details/components/Applications/index.tsx
  src/pages/stage-details/components/Applications/types.ts
  src/pages/stage-details/components/ApplicationsWrapper/index.tsx
  src/pages/stage-details/hooks/useInfoColumns.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/providers/DynamicData/context.ts
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/types.ts
  src/providers/Dialog/mapping.tsx
  src/utils/formFieldValidation.ts
  src/widgets/ConfirmModal/constants.ts
  src/widgets/ConfirmModal/index.tsx
  src/widgets/ConfirmModal/types.ts
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditStage/components/Create/components/Form/index.tsx
  src/widgets/CreateEditStage/components/Edit/components/Form/index.tsx
  src/widgets/CreateEditStage/components/Edit/hooks/useDefaultValues.ts
  src/widgets/CreateEditStage/components/fields/CleanTemplate/index.tsx
  src/widgets/CreateEditStage/components/fields/DeployTemplate/index.tsx
  src/widgets/CreateEditStage/components/fields/index.ts
  src/widgets/CreateEditStage/names.ts
  src/widgets/ManageCodeMie/hooks/useCodemieProjectEditForm.ts
Labels: feature

#320 feat: Update pipelines table and filter
  src/constants/pipelineTypes.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateAutotestRunnerPipelineRun.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createAutotestRunnerPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createAutotestRunnerPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Details/index.tsx
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/pipelines/components/PipelineRunList/index.tsx
  src/pages/pipelines/constants.ts
  src/pages/pipelines/page.tsx
  src/pages/pipelines/providers/Permissions/provider.tsx
  src/pages/pipelines/types.ts
  src/pages/pipelines/view.tsx
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
  src/pages/stage-details/components/Applications/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/providers/DynamicData/context.ts
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/types.ts
  src/widgets/ManageCodeMie/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageCodeMie/hooks/useCodemieProjectEditForm.ts
  src/widgets/PipelineRunList/constants.ts
  src/widgets/PipelineRunList/hooks/useUpperColumns.tsx
  src/widgets/PipelineRunList/index.tsx
  src/widgets/PipelineRunList/types.ts
Labels: enhancement, feature

#324 feat: Add codebase codemie integration
  mocks/headlamp-plugin/lib/K8s/cluster.ts
  src/k8s/groups/EDP/Codebase/hooks/useCodebaseCRUD.tsx
  src/k8s/groups/EDP/Codebase/labels.ts
  src/k8s/groups/EDP/Codebase/utils/createCodebaseInstance/index.ts
  src/widgets/AIChat/components/Chat/index.tsx
  src/widgets/CreateEditCodebase/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCodebase/components/Create/components/Inner/components/Form/components/Advanced/index.tsx
  src/widgets/CreateEditCodebase/components/Edit/components/Form/hooks/useUpdateJiraServerIntegrationValue.ts
  src/widgets/CreateEditCodebase/components/Edit/components/Form/index.tsx
  src/widgets/CreateEditCodebase/components/Edit/hooks/useDefaultValues.ts
  src/widgets/CreateEditCodebase/components/fields/CodemieIntegration/index.tsx
  src/widgets/CreateEditCodebase/names.ts
Labels: enhancement, feature

#327 feat: Update genai codemie page
  src/k8s/groups/EDP/Codemie/constants.ts
  src/k8s/groups/EDP/Codemie/index.ts
  src/k8s/groups/EDP/Codemie/utils/createCodemieSecretInstance/index.test.ts
  src/k8s/groups/EDP/Codemie/utils/createCodemieSecretInstance/index.ts
  src/k8s/groups/EDP/CodemieProject/index.ts
  src/k8s/groups/EDP/CodemieProject/types.ts
  src/k8s/groups/EDP/CodemieProject/utils/createCodemieProjectInstance/index.test.ts
  src/k8s/groups/EDP/CodemieProject/utils/createCodemieProjectInstance/index.ts
  src/k8s/groups/EDP/CodemieProjectSettings/utils/createCodemieProjectSettingsInstance/index.test.ts
  src/k8s/groups/EDP/CodemieProjectSettings/utils/createCodemieProjectSettingsInstance/index.ts
  src/k8s/groups/EDP/CodemieProjectSettings/utils/createCodemieProjectSettingsSecretInstance/index.test.ts
  src/k8s/groups/EDP/CodemieProjectSettings/utils/createCodemieProjectSettingsSecretInstance/index.ts
  src/k8s/groups/default/Secret/labels.ts
  src/pages/configuration/pages/codemie/providers/DynamicData/context.ts
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/codemie/providers/DynamicData/types.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/widgets/ManageCodeMie/components/CodemieProject/fields/ProjectName/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProject/fields/index.ts
  src/widgets/ManageCodeMie/components/CodemieProject/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/fields/Alias/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/fields/TokenName/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/fields/Type/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/fields/URL/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/fields/index.ts
  src/widgets/ManageCodeMie/components/CodemieProjectSettings/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettingsSecret/fields/Token/index.tsx
  src/widgets/ManageCodeMie/components/CodemieProjectSettingsSecret/fields/index.ts
  src/widgets/ManageCodeMie/components/CodemieProjectSettingsSecret/index.tsx
  src/widgets/ManageCodeMie/constants.ts
  src/widgets/ManageCodeMie/hooks/useCodemieProjectCreateForm.ts
  src/widgets/ManageCodeMie/hooks/useCodemieProjectEditForm.ts
  src/widgets/ManageCodeMie/hooks/useCodemieProjectSettingsCreateForm.ts
  src/widgets/ManageCodeMie/hooks/useCodemieProjectSettingsEditForm.ts
  src/widgets/ManageCodeMie/hooks/useCodemieSettingsSecretCreateForm.ts
  src/widgets/ManageCodeMie/hooks/useCodemieSettingsSecretEditForm.ts
  src/widgets/ManageCodeMie/index.tsx
  src/widgets/ManageCodeMie/names.ts
  src/widgets/ManageCodeMie/providers/Data/context.ts
  src/widgets/ManageCodeMie/providers/Data/index.tsx
  src/widgets/ManageCodeMie/providers/Data/types.ts
  src/widgets/ManageCodeMie/types.ts
Labels: enhancement

#328 chore: Update KubeRocketCI names and documentation links (#325)
  .github/workflows/release.yaml
  README.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  deploy-templates/values.yaml
Labels: routine

#330 fix: Fix bugs on pipelines page
  src/k8s/groups/EDP/CodemieProjectSettings/constants.ts
  src/k8s/groups/EDP/CodemieProjectSettings/index.ts
  src/k8s/groups/EDP/CodemieProjectSettings/types.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
  src/widgets/PipelineRunList/index.tsx
Labels: bug, enhancement

#329 chore: Update KubeRocketCI names and documentation links (#325)
  deploy-templates/values.yaml
Labels: routine

#332 fix: Sanitize CodeMie html
  src/k8s/groups/default/Secret/utils/createChatAssistantIntegrationSecretInstance/index.test.ts
  src/k8s/groups/default/Secret/utils/createChatAssistantIntegrationSecretInstance/index.ts
  src/widgets/AIChat/components/Chat/index.tsx
  src/widgets/AIChat/utils/sanitizeMessage.ts
Labels: CodeMie

#334 feat: Update labels
  src/k8s/groups/EDP/Codemie/index.ts
  src/k8s/groups/EDP/Codemie/types.ts
  src/pages/cdpipeline-details/components/StageList/index.tsx
  src/pages/cdpipeline-details/components/StageListFilter/index.tsx
  src/pages/cdpipeline-details/route.tsx
  src/pages/cdpipeline-details/view.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/cdpipeline-list/route.tsx
  src/pages/cdpipeline-list/view.tsx
  src/pages/overview-list/components/CDPipelinesGraph/index.tsx
  src/pages/overview-list/components/StagesGraph/index.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/route.tsx
  src/pages/stage-details/view.tsx
  src/routes/names.ts
  src/routes/sidebar-list.ts
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/components/Create/components/DialogHeader/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/Applications/index.tsx
  src/widgets/CreateEditCodebase/components/fields/CodemieIntegration/index.tsx
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/components/Create/components/DialogHeader/index.tsx
  src/widgets/CreateEditStage/components/fields/StageName/index.tsx
Labels: enhancement, feature

#336 feat: Add c and cpp langs
  src/configs/codebase-mappings/application/index.ts
  src/configs/codebase-mappings/index.ts
  src/configs/icon-mappings/index.ts
  src/icons/sprites/Resources/index.tsx
  src/icons/sprites/Resources/names.ts
  src/icons/sprites/Resources/symbols/C.tsx
  src/icons/sprites/Resources/symbols/CPP.tsx
  src/icons/sprites/Resources/symbols/Cmake.tsx
  src/icons/sprites/Resources/symbols/Make.tsx
  src/icons/sprites/Resources/symbols/None.tsx
  src/icons/sprites/Resources/symbols/index.ts
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/cdpipeline-list/view.tsx
  src/widgets/CDPipelineActionsMenu/index.tsx
  src/widgets/CodebaseActionsMenu/index.tsx
  src/widgets/CodebaseBranchActions/components/CodebaseBranchCDPipelineConflictError/index.tsx
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/Applications/index.tsx
  src/widgets/CreateEditCDPipeline/constants.ts
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/components/fields/CleanTemplate/index.tsx
  src/widgets/CreateEditStage/components/fields/Cluster/index.tsx
  src/widgets/CreateEditStage/components/fields/Description/index.tsx
  src/widgets/CreateEditStage/components/fields/Namespace/index.tsx
  src/widgets/CreateEditStage/components/fields/QualityGates/index.tsx
  src/widgets/CreateEditStage/components/fields/StageName/index.tsx
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/StageActionsMenu/utils.ts
Labels: enhancement, feature

#338 fix: Update pipelines filter
  src/widgets/PipelineRunList/constants.ts
Labels: enhancement

#341 feat: Update pipeline links
  src/constants/urls.ts
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
  src/pages/component-details/components/Pipeline/index.tsx
  src/pages/configuration/pages/pipeline-details/types.ts
  src/pages/configuration/pages/pipeline-list/constants.ts
  src/services/link-creation/index.ts
  src/services/link-creation/tekton/index.test.ts
  src/services/link-creation/tekton/index.ts
  src/widgets/PipelineRunGraphDialog/hooks/useInfoRows.tsx
  src/widgets/PipelineRunGraphDialog/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: enhancement

#343 feat: Add codemie applications
  src/k8s/groups/EDP/CodemieApplication/config.ts
  src/k8s/groups/EDP/CodemieApplication/constants.ts
  src/k8s/groups/EDP/CodemieApplication/index.ts
  src/k8s/groups/EDP/CodemieApplication/types.ts
  src/pages/configuration/pages/codemie/providers/DynamicData/context.ts
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/codemie/providers/DynamicData/types.ts
  src/pages/configuration/pages/codemie/view.tsx
Labels: enhancement, feature

#345 feat: Add action success modals
  src/components/Snackbar/index.tsx
  src/k8s/groups/EDP/Codebase/hooks/useCodebaseCRUD.tsx
  src/k8s/groups/EDP/Stage/hooks/useCreateCDPipelineStage.tsx
  src/k8s/groups/Tekton/PipelineRun/index.ts
  src/k8s/groups/Tekton/PipelineRun/types.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/TaskRun/hooks/useStreamTaskRunListByPipelineNameAndPipelineType.tsx
  src/k8s/groups/Tekton/TaskRun/index.ts
  src/k8s/groups/Tekton/TaskRun/types.ts
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
  src/pages/configuration/pages/chat-assistant/view.tsx
  src/pages/pipeline-details/components/Details/components/MenuAccordion/index.tsx
  src/pages/pipeline-details/providers/DynamicData/provider.tsx
  src/widgets/CreateCodebaseFromTemplate/components/FormActions/index.tsx
  src/widgets/CreateCodebaseFromTemplate/index.tsx
  src/widgets/CreateEditCodebase/components/Create/components/Inner/components/FormActions/index.tsx
  src/widgets/CreateEditStage/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditStage/types.ts
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/SuccessModal/index.tsx
  src/widgets/SuccessModal/types.ts
Labels: enhancement, feature

#347 chore: Update Dockerfile base image (#346)
  Dockerfile
Labels: enhancement

#353 fix: Fix nonexistant pipeline diagram btn
  src/widgets/dialogs/ManageStage/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageStage/components/fields/CleanTemplate/index.tsx
  src/widgets/dialogs/ManageStage/components/fields/DeployTemplate/index.tsx
Labels: bug
