Repository epam/edp-headlamp, pull requests merged in 2024-04, with the labels that each got.

#191 chore: Migrate headlamp from gerrit to github
  .github/workflows/pr.yaml
Labels: dependencies

#196 chore: Add codeowners file to the repo
  CODEOWNERS
Labels: enhancement

#199 fix: Fix gitops values yaml file link
  Dockerfile
  src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/edp-stage-details/providers/DynamicData/context.ts
  src/pages/edp-stage-details/providers/DynamicData/provider.tsx
  src/pages/edp-stage-details/providers/DynamicData/types.ts
  src/widgets/ManageGitServer/index.tsx
Labels: bug

#201 feat: Fix scroll container, fix image versions order etc
  src/components/HorizontalScrollContainer/index.tsx
  src/k8s/EDPCodebaseImageStream/utils/createImageStreamTags/index.test.ts
  src/k8s/EDPCodebaseImageStream/utils/createImageStreamTags/index.ts
  src/pages/edp-configuration/pages/edp-dependency-track-integration/constants.ts
  src/pages/edp-configuration/pages/edp-jira-integration/constants.ts
  src/pages/edp-configuration/pages/edp-sonar-integration/constants.ts
  src/pages/edp-stage-details/components/Applications/components/ValuesOverrideCheckbox/index.tsx
Labels: bug

#204 chore: Update package json file, docker img (#203)
  Dockerfile
  package-lock.json
  package.json
  src/Logo.svg
  src/pages/edp-configuration/pages/edp-sso-integration/view.tsx
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/widgets/CreateCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/CreateCodebaseFromTemplate/__snapshots__/index.test.tsx.snap
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCodebase/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCodebase/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCodebase/components/Create/components/Selection/index.tsx
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap
  src/widgets/DeleteKubeObject/__snapshots__/index.test.tsx.snap
  src/widgets/ManageArgoCDCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageArgoCDCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageArgoCDCI/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDefectDojoCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDefectDojoCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDefectDojoCI/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageDependencyTrackCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDependencyTrackCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDependencyTrackCI/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageGitOps/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitOps/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageJiraCI/components/Edit/components/FormActions/index.tsx
  src/widgets/ManageNexusCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageNexusCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageNexusCI/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageSSOCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageSSOCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageSSOCI/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageSonarCI/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageSonarCI/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageSonarCI/__snapshots__/index.read.test.tsx.snap
Labels: enhancement, tech debt

#214 chore: Update headlamp image tag
  .github/workflows/pr.yaml
  Dockerfile
  package.json
  src/pages/edp-stage-details/providers/DynamicData/provider.tsx
Labels: enhancement

#221 chore: Remove unused CI flow
  .github/workflows/ci.yaml
Labels: dependencies
