Repository epam/edp-headlamp, pull requests merged in 2024-11, with the labels that each got.

#457 feat: Add permission check for approve button
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx
  src/pages/pipeline-details/constants.ts
Labels: enhancement

#459 chore: Update current development version (#458)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#464 feat: Update clean deploy pipeline creation
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
Labels: enhancement

#466 feat: Remove type password fields autocomplete
  src/providers/Form/components/FormTextFieldPassword/index.tsx
  src/widgets/ManageArgoCD/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageArgoCD/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageArgoCD/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageChatAssistant/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageChatAssistant/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageChatAssistant/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDefectDojo/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDefectDojo/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDefectDojo/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageDependencyTrack/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDependencyTrack/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageDependencyTrack/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageJiraServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageJiraServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageJiraServer/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageNexus/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageNexus/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageNexus/__snapshots__/index.read.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageSonar/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageSonar/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageSonar/__snapshots__/index.read.test.tsx.snap
Labels: enhancement

#470 feat: Open auth in new tab
  Dockerfile
Labels: enhancement

#472 fix: Stage namespace regexp
  src/widgets/ManageGitServer/components/GitServer/components/fields/Name/index.tsx
  src/widgets/ManageGitServer/components/GitServer/components/fields/UserName/SSHPort/index.tsx
  src/widgets/dialogs/ManageStage/components/fields/Namespace/index.tsx
Labels: bug

#474 fix: Kibana link
  src/services/link-creation/kibana/index.test.ts
  src/services/link-creation/kibana/index.ts
Labels: bug, enhancement

#476 feat: Update tooltips, add task timings, fix diagram links
  Dockerfile
  src/override.css
  src/pages/component-details/page.tsx
  src/pages/component-details/view.tsx
  src/pages/configuration/pages/pipeline-details/page.tsx
  src/pages/configuration/pages/pipeline-details/view.tsx
  src/pages/configuration/pages/task-details/page.tsx
  src/pages/configuration/pages/task-details/view.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/components/TaskRunStep/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/hooks/useTabs.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/types.ts
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/TaskRun/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/index.tsx
  src/pages/pipeline-details/components/Details/index.tsx
  src/pages/pipeline-details/hooks/useTabs.tsx
  src/pages/pipeline-details/page.tsx
  src/pages/pipeline-details/view.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/components/Variables/index.tsx
  src/pages/stage-details/page.tsx
  src/pages/stage-details/view.tsx
  src/providers/Tabs/components/Tabs/index.tsx
  src/providers/Tabs/components/Tabs/styles.ts
  src/providers/Tabs/components/Tabs/types.ts
  src/providers/Tabs/context.ts
  src/providers/Tabs/hooks.ts
  src/providers/Tabs/provider.tsx
  src/providers/Tabs/types.ts
  src/widgets/PipelineRunGraph/index.tsx
  src/widgets/PipelineRunGraph/types.ts
  src/widgets/dialogs/PodsLogViewer/index.tsx
  src/widgets/dialogs/PodsTerminal/index.tsx
Labels: bug, enhancement, feature

#477 fix: Update kibana link
  src/services/link-creation/kibana/index.test.ts
  src/services/link-creation/kibana/index.ts
Labels: bug, enhancement

#482 fix: Page loadings
  src/k8s/groups/EDP/Codebase/hooks/useEnrichedApplicationsWithImageStreamsQuery.ts
  src/pages/cdpipeline-details/providers/DynamicData/provider.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
  src/pages/component-details/hooks/usePageTabs.tsx
  src/pages/component-details/providers/Data/provider.tsx
  src/pages/component-details/providers/DynamicData/context.ts
  src/pages/component-details/providers/DynamicData/provider.tsx
  src/pages/component-details/providers/DynamicData/types.ts
  src/pages/component-details/utils.ts
  src/pages/configuration/pages/argocd/view.tsx
  src/pages/configuration/pages/chat-assistant/view.tsx
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/defect-dojo/view.tsx
  src/pages/configuration/pages/dependency-track/view.tsx
  src/pages/configuration/pages/gitops/view.tsx
  src/pages/configuration/pages/gitservers/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/jira/view.tsx
  src/pages/configuration/pages/nexus/view.tsx
  src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/sonar/view.tsx
  src/pages/pipeline-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/widgets/AIChat/index.tsx
Labels: bug

#484 fix: Health check alert, stage variables empty list
  Dockerfile
  src/pages/stage-details/components/Variables/index.tsx
Labels: bug

#486 fix: Bugs after latest update
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Actions/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Actions/types.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/types.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/types.ts
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
  src/pages/component-details/providers/DynamicData/context.ts
  src/pages/component-details/providers/DynamicData/provider.tsx
  src/pages/component-details/providers/DynamicData/types.ts
  src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/hooks/useTabs.tsx
  src/pages/pipeline-details/page.tsx
  src/pages/stage-details/view.tsx
  src/providers/Tabs/hooks.ts
  src/services/link-creation/git/index.ts
  src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx
  src/widgets/PodsLogViewer/types.ts
Labels: bug

#488 fix: Edit branch
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
Labels: bug

#490 feat: Add resource quotas widget
  src/components/TileChart/index.tsx
  src/index.tsx
  src/k8s/groups/default/ResourceQuota/config.ts
  src/k8s/groups/default/ResourceQuota/index.ts
  src/k8s/groups/default/ResourceQuota/labels.ts
  src/k8s/groups/default/ResourceQuota/types.ts
  src/widgets/ResourceQuotas/components/CircleProgress/index.tsx
  src/widgets/ResourceQuotas/components/CircleProgress/types.ts
  src/widgets/ResourceQuotas/index.tsx
  src/widgets/ResourceQuotas/types.ts
  src/widgets/ResourceQuotas/utils.ts
Labels: feature

#495 fix: Component crash, tekton 404 pages
  src/pages/component-details/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/pipeline-details/view.tsx
  src/pages/configuration/pages/task-details/view.tsx
Labels: bug

#497 feat: Hide manual qg name field
  src/widgets/dialogs/ManageStage/components/fields/QualityGates/components/QualityGateRow/index.tsx
  src/widgets/dialogs/ManageStage/components/fields/QualityGates/constants.ts
Labels: enhancement

#499 fix: Refactor notifications
  src/hooks/useResourceCRUDMutation/index.test.tsx
  src/hooks/useResourceCRUDMutation/index.ts
  src/hooks/useResourceCRUDMutation/index.tsx
  src/hooks/useResourceRequestStatusMessages/index.tsx
  src/k8s/groups/ArgoCD/Application/hooks/useArgoApplicationCRUD.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateDeployPipelineRun.ts
  src/k8s/groups/default/ResourceQuota/types.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/PipelineRunList/components/DeleteDialog/index.tsx
  src/widgets/ResourceQuotas/types.ts
Labels: bug, enhancement

#500 feat: Update rq logic and notis
  Dockerfile
  src/components/ErrorBoundary/index.tsx
  src/components/Snackbar/index.tsx
  src/hooks/useResourceCRUDMutation/index.tsx
  src/hooks/useResourceRequestStatusMessages/index.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateDeployPipelineRun.tsx
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/utils/createRandomString.ts
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/PipelineRunList/hooks/useUpperColumns.tsx
  src/widgets/PipelineRunList/index.tsx
  src/widgets/ResourceQuotas/index.tsx
  src/widgets/ResourceQuotas/utils.ts
Labels: enhancement

#502 feat: Add test attrs in variables form
  src/pages/stage-details/components/Variables/index.tsx
Labels: routine

#504 feat: Add deployment flow RQs (#503)
  src/k8s/groups/default/ResourceQuota/index.ts
  src/k8s/groups/default/ResourceQuota/types.ts
  src/widgets/ResourceQuotas/components/RQItem/index.tsx
  src/widgets/ResourceQuotas/index.tsx
Labels: enhancement, feature

#506 feat: Add reserve logs
  src/components/LogViewer/index.tsx
  src/k8s/groups/default/ConfigMap/hooks/useEDPConfigMap.ts
  src/k8s/groups/default/ConfigMap/index.ts
  src/pages/pipeline-details/providers/DynamicData/context.ts
  src/pages/pipeline-details/providers/DynamicData/provider.tsx
  src/pages/pipeline-details/providers/DynamicData/types.ts
  src/pages/pipeline-details/view.tsx
  src/services/api/index.ts
Labels: feature

#507 feat: Improve reserve logs
  src/components/ErrorContent/index.tsx
  src/k8s/groups/Tekton/Task/index.ts
  src/k8s/groups/Tekton/Task/types.ts
  src/pages/pipeline-details/components/ReserveLogs/index.tsx
  src/pages/pipeline-details/components/ReserveLogs/types.ts
  src/pages/pipeline-details/providers/DynamicData/context.ts
  src/pages/pipeline-details/providers/DynamicData/logs.query.ts
  src/pages/pipeline-details/providers/DynamicData/provider.tsx
  src/pages/pipeline-details/providers/DynamicData/types.ts
  src/pages/pipeline-details/providers/DynamicData/utils.ts
  src/pages/pipeline-details/view.tsx
Labels: enhancement
