Repository epam/edp-headlamp, pull requests merged in 2024-10, with the labels that each got.

#405 feat: Add env variables section
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/stage-details/components/Variables/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/providers/DynamicData/context.ts
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/types.ts
Labels: enhancement, feature

#406 docs: Update changelog file for release notes (#382)
  CHANGELOG.md
Labels: documentation

#408 feat: Update env variables to use configmap
  src/pages/stage-details/components/Variables/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/providers/DynamicData/context.ts
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/types.ts
Labels: enhancement

#410 fix: Fix multi ns errors
  .prettierrc
  src/components/DataGrid/index.tsx
  src/components/DataGrid/types.ts
  src/components/Table/components/TableBody/index.tsx
  src/components/Table/components/TableBody/types.ts
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/types.ts
  src/pages/cdpipeline-list/page.tsx
  src/pages/cdpipeline-list/providers/DynamicData/context.ts
  src/pages/cdpipeline-list/providers/DynamicData/hooks.ts
  src/pages/cdpipeline-list/providers/DynamicData/provider.tsx
  src/pages/cdpipeline-list/providers/DynamicData/types.ts
  src/pages/cdpipeline-list/view.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/component-list/components/ComponentList/index.tsx
  src/pages/component-list/page.tsx
  src/pages/component-list/providers/DynamicData/context.ts
  src/pages/component-list/providers/DynamicData/hooks.ts
  src/pages/component-list/providers/DynamicData/provider.tsx
  src/pages/component-list/providers/DynamicData/types.ts
  src/pages/configuration/pages/clusters/view.tsx
  src/pages/configuration/pages/pipeline-list/view.tsx
  src/pages/configuration/pages/quicklinks/components/ComponentList/index.tsx
  src/pages/configuration/pages/quicklinks/components/ComponentList/types.ts
  src/pages/configuration/pages/quicklinks/view.tsx
  src/pages/configuration/pages/task-list/view.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/index.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/types.ts
  src/pages/marketplace/components/MarketplaceList/index.tsx
  src/pages/marketplace/page.tsx
  src/pages/marketplace/providers/DynamicData/context.ts
  src/pages/marketplace/providers/DynamicData/hooks.ts
  src/pages/marketplace/providers/DynamicData/provider.tsx
  src/pages/marketplace/providers/DynamicData/types.ts
  src/pages/overview-list/components/CDPipelinesGraph/hooks/useCDPipelinesGraphData.ts
  src/pages/overview-list/components/CodebaseBranchesGraph/hooks/useCodebaseBranchesGraphData.ts
  src/pages/overview-list/components/CodebasesGraph/hooks/useCodebasesGraphData.ts
  src/pages/overview-list/components/PipelineRunsGraph/hooks/usePipelineRunsGraphData.ts
  src/pages/overview-list/components/StagesGraph/hooks/useStagesGraphData.ts
  src/pages/pipelines/page.tsx
  src/pages/pipelines/providers/DynamicData/context.ts
  src/pages/pipelines/providers/DynamicData/hooks.ts
  src/pages/pipelines/providers/DynamicData/provider.tsx
  src/pages/pipelines/providers/DynamicData/types.ts
  src/pages/pipelines/view.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/widgets/PipelineList/index.tsx
  src/widgets/PipelineRunList/index.tsx
  src/widgets/PipelineRunList/types.ts
  src/widgets/TaskList/index.tsx
Labels: bug, enhancement

#415 fix: Fix to promote default values
  src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
Labels: bug

#417 fix: Try fix tests crash on prod
  src/pages/cdpipeline-details/components/CDPipelineApplicationsTable/hooks/useColumns.tsx
  src/pages/cdpipeline-details/providers/DynamicData/provider.tsx
  src/widgets/dialogs/ManageCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/dialogs/ManageStage/components/Create/components/FormActions/index.tsx
  src/widgets/dialogs/ManageStage/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageStage/components/fields/StageName/index.tsx
Labels: bug

#419 fix: Try fix redirect after auth
  Dockerfile
  src/pages/cdpipeline-list/view.tsx
Labels: bug, enhancement

#420 fix: Fix redirect after auth
  Dockerfile
Labels: bug, enhancement

#422 fix: Fix pipelines
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/widgets/PipelineRunList/components/DeleteDialog/index.tsx
Labels: bug

#424 feat: Update approve reject
  src/configs/select-options/triggerTypes.ts
  src/constants/triggerTypes.ts
  src/icons/iconify-icons-mapping.ts
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/constants.ts
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/types.ts
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/index.tsx
  src/widgets/dialogs/ManageCDPipeline/providers/CurrentDialog/provider.tsx
Labels: enhancement, feature

#426 fix: No branch crash, registry create, login redirect
  Dockerfile
  src/widgets/ManageRegistry/hooks/useConfigMapEditForm.ts
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx
Labels: bug

#430 fix: Requests caching
  src/components/PageLogicWrapper/index.tsx
Labels: bug

#431 feat: Add krakend backend integration
  src/pages/component-details/providers/Data/provider.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/index.tsx
  src/services/api/index.ts
Labels: enhancement, feature

#433 feat: Update deployment flow promote
  src/providers/Form/components/FormSwitch/index.tsx
  src/providers/Form/components/FormSwitch/types.ts
  src/services/api/index.ts
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
  src/widgets/dialogs/ManageCDPipeline/names.ts
Labels: enhancement, feature

#434 fix: To promote default value
  src/widgets/dialogs/ManageCDPipeline/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts
Labels: bug, enhancement

#436 chore: Add annotation to control pod seesion timeout(#435)
  deploy-templates/README.md
  deploy-templates/values.yaml
Labels: enhancement

#438 feat: Set edp as default versioning type
  src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts
Labels: enhancement

#440 chore: Update current development version (#439)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#442 fix: Add validation for name field
  src/widgets/ManageGitServer/components/GitServer/components/fields/Name/index.tsx
Labels: enhancement

#444 feat: Improve applications table update
  src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/providers/Form/components/FormSelect/index.tsx
  src/providers/Form/components/FormSelect/types.ts
Labels: enhancement

#446 feat: Improve pods features
  src/k8s/groups/default/Pod/config.ts
  src/k8s/groups/default/Pod/index.ts
  src/k8s/groups/default/Pod/types.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/types.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/providers/DynamicData/context.ts
  src/pages/stage-details/providers/DynamicData/provider.tsx
  src/pages/stage-details/providers/DynamicData/types.ts
  src/widgets/dialogs/PodsLogViewer/index.tsx
  src/widgets/dialogs/PodsLogViewer/types.ts
  src/widgets/dialogs/PodsTerminal/index.tsx
  src/widgets/dialogs/PodsTerminal/types.ts
Labels: enhancement, feature

#447 chore: Update Pull Request Template (#234)
  pull_request_template.md
Labels: enhancement

#451 feat: Show version diff marker
  src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx
Labels: enhancement

#455 feat: Implement OIDC integration with Microsoft Entra IdP (#454)
  deploy-templates/README.md
  deploy-templates/templates/deployment.yaml
  deploy-templates/values.yaml
Labels: feature
