Repository epam/edp-headlamp, pull requests merged in 2024-05, with the labels that each got.

#229 fix: Fix pipelines filter, fix integration forms
  src/components/Table/components/TablePagination/index.tsx
  src/pages/edp-configuration/pages/edp-dependency-track-integration/view.tsx
  src/pages/edp-overview-list/page.tsx
  src/pages/edp-pipelines/components/PipelineRunList/index.tsx
  src/pages/edp-pipelines/constants.ts
  src/pages/edp-pipelines/page.tsx
  src/pages/edp-pipelines/types.ts
  src/widgets/ManageDefectDojo/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageDependencyTrack/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageNexus/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageSonar/components/QuickLink/fields/ExternalURL/index.tsx
Labels: bug

#233 feat: Add pipeline page
  src/components/Editor/index.tsx
  src/components/LogViewer/index.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/styles.ts
  src/components/Tabs/types.ts
  src/k8s/PipelineRun/hooks/usePipelineRunData.ts
  src/k8s/TaskRun/index.ts
  src/k8s/TaskRun/types.ts
  src/k8s/TaskRun/utils/getStatus/index.ts
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TabContent/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/hooks/useTabs.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/styles.ts
  src/pages/edp-pipeline-details/page.tsx
  src/pages/edp-pipeline-details/providers/DynamicData/context.ts
  src/pages/edp-pipeline-details/providers/DynamicData/hooks.ts
  src/pages/edp-pipeline-details/providers/DynamicData/provider.tsx
  src/pages/edp-pipeline-details/providers/DynamicData/types.ts
  src/pages/edp-pipeline-details/route.tsx
  src/pages/edp-pipeline-details/styles.ts
  src/pages/edp-pipeline-details/types.ts
  src/pages/edp-pipeline-details/view.tsx
  src/pages/edp-pipelines/constants.ts
  src/pages/edp-pipelines/types.ts
  src/routes/index.tsx
  src/widgets/LogViewer/index.tsx
  src/widgets/PipelineRunGraph/hooks/usePipelineRunGraphData.ts
  src/widgets/PipelineRunGraph/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/PipelineRunList/hooks/useUpperColumns.tsx
Labels: feature

#239 feat: Add GHCR as Container Registry option flow (#238)
  src/configs/icon-mappings/index.ts
  src/icons/iconify-icons-mapping.ts
  src/k8s/ConfigMap/constants.ts
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
  src/pages/edp-pipelines/constants.ts
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/providers/MultiForm/index.tsx
  src/widgets/ManageArgoCD/hooks/useQuickLinkEditForm.ts
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageRegistry/components/ConfigMap/fields/Type/index.tsx
  src/widgets/ManageRegistry/constants.ts
  src/widgets/ManageRegistry/hooks/useConfigMapEditForm.ts
  src/widgets/ManageRegistry/hooks/usePullAccountCreateForm.ts
  src/widgets/ManageRegistry/hooks/usePullAccountEditForm.ts
  src/widgets/ManageRegistry/hooks/usePushAccountCreateForm.ts
  src/widgets/ManageRegistry/hooks/usePushAccountEditForm.ts
  src/widgets/ManageRegistry/hooks/useResetRegistry.ts
  src/widgets/ManageRegistry/index.edit.test.tsx
  src/widgets/ManageRegistry/index.tsx
  src/widgets/PipelineRunGraph/hooks/usePipelineRunGraphData.ts
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: feature

#241 fix: Fix branch validation, fix integrations labels
  Dockerfile
  src/widgets/CreateCodebaseBranch/components/fields/BranchName/index.tsx
  src/widgets/CreateCodebaseBranch/components/fields/ReleaseBranchName/index.tsx
  src/widgets/ManageDefectDojo/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageDefectDojo/components/Secret/fields/Token/index.tsx
  src/widgets/ManageDependencyTrack/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageDependencyTrack/components/Secret/fields/Token/index.tsx
  src/widgets/ManageSonar/components/QuickLink/fields/ExternalURL/index.tsx
  src/widgets/ManageSonar/components/Secret/fields/Token/index.tsx
Labels: bug, routine, tech debt

#243 feat: Update GitServer form (#242)
  src/k8s/EDPGitServer/types.ts
  src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/context.ts
  src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/provider.tsx
  src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/types.ts
  src/pages/edp-configuration/pages/edp-gitserver-list/view.tsx
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitServer/components/GitServer/components/fields/OverrideWebHookURL/index.tsx
  src/widgets/ManageGitServer/components/GitServer/components/fields/UserName/SSHPort/index.tsx
  src/widgets/ManageGitServer/components/GitServer/components/fields/WebHookURL/index.tsx
  src/widgets/ManageGitServer/components/GitServer/components/fields/index.ts
  src/widgets/ManageGitServer/components/GitServer/index.tsx
  src/widgets/ManageGitServer/hooks/useGitServerCreateForm.ts
  src/widgets/ManageGitServer/hooks/useGitServerEditForm.ts
  src/widgets/ManageGitServer/index.create.test.tsx
  src/widgets/ManageGitServer/index.edit.test.tsx
  src/widgets/ManageGitServer/index.tsx
  src/widgets/ManageGitServer/names.ts
  src/widgets/ManageGitServer/types.ts
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageRegistry/components/ConfigMap/fields/RegistryEndpoint/index.tsx
  src/widgets/ManageRegistry/components/ConfigMap/fields/RegistrySpace/index.tsx
  src/widgets/PipelineRunGraph/hooks/usePipelineRunGraphData.ts
Labels: bug, feature

#244 feat: Update pipeline page
  src/components/ActionsInlineList/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx
  src/pages/edp-pipeline-details/view.tsx
  src/widgets/LogViewer/index.tsx
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/PipelineRunList/components/DeleteDialog/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/PipelineRunList/index.tsx
Labels: enhancement

#246 fix: Enable deploy btn when all apps are selected
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: bug

#235 feat: Add pull request templates for github issues(#234)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  pull_request_template.md
Labels: enhancement

#248 feat: Update warning messages and bugfixes
  src/components/ErrorContent/index.tsx
  src/components/LogViewer/index.tsx
  src/components/TileChart/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx
  src/pages/edp-stage-details/components/Applications/components/ValuesOverrideCheckbox/index.tsx
  src/pages/edp-stage-details/components/Applications/hooks/useUpperColumns.tsx
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/widgets/ManageGitServer/components/GitServer/components/fields/OverrideWebHookURL/index.tsx
  src/widgets/ManageGitServer/hooks/useGitServerEditForm.ts
  src/widgets/ManageRegistry/components/ConfigMap/fields/RegistrySpace/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: bug, enhancement

#250 feat: Add permissions check for actions
  src/components/ActionsMenuList/index.tsx
  src/components/ErrorContent/index.tsx
  src/constants/resourceActions.ts
  src/utils/actions/createKubeAction/index.ts
  src/widgets/CDPipelineActionsMenu/index.tsx
  src/widgets/CodebaseActionsMenu/index.tsx
  src/widgets/CodebaseBranchActions/index.tsx
  src/widgets/CodebaseBranchActions/utils.ts
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/QuickLinkActionsMenu/index.tsx
  src/widgets/StageActionsMenu/index.tsx
  src/widgets/StageActionsMenu/utils.ts
Labels: feature

#251 fix: Permission check fixes, pipeline fixes, crash fixes
  src/components/ButtonWithPermission/index.tsx
  src/pages/edp-cdpipeline-details/components/StageListFilter/index.tsx
  src/pages/edp-cdpipeline-list/view.tsx
  src/pages/edp-component-details/components/CodebaseBranchesList/components/TableHeaderActions/index.tsx
  src/pages/edp-component-list/components/ComponentListFilter/index.tsx
  src/pages/edp-configuration/pages/edp-quick-link-list/view.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/index.tsx
  src/pages/edp-pipelines/components/PipelineRunList/index.tsx
  src/pages/edp-pipelines/constants.ts
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/utils/actions/createKubeAction/index.ts
  src/widgets/CDPipelineActionsMenu/index.tsx
  src/widgets/CodebaseActionsMenu/index.tsx
  src/widgets/CodebaseBranchActions/index.tsx
  src/widgets/ManageRegistry/components/ConfigMap/fields/RegistryEndpoint/index.tsx
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/QuickLinkActionsMenu/index.tsx
  src/widgets/StageActionsMenu/index.tsx
  src/widgets/StageActionsMenu/utils.ts
Labels: bug

#228 feat: Align chart for ingress TLS configuration(#227)
  deploy-templates/README.md
  deploy-templates/templates/_helpers.tpl
  deploy-templates/templates/ingress.yaml
  deploy-templates/values.yaml
Labels: bug, enhancement
