Repository epam/edp-headlamp, pull requests merged in 2024-12, with the labels that each got.

#508 feat: Improve reserve logs
  src/k8s/groups/default/ResourceQuota/index.ts
  src/pages/pipeline-details/components/ReserveLogs/components/AllLogs/index.tsx
  src/pages/pipeline-details/components/ReserveLogs/components/AllLogs/types.ts
  src/pages/pipeline-details/components/ReserveLogs/components/LogsByTask/index.tsx
  src/pages/pipeline-details/components/ReserveLogs/components/LogsByTask/types.ts
  src/pages/pipeline-details/components/ReserveLogs/hooks/useTabs.tsx
  src/pages/pipeline-details/components/ReserveLogs/index.tsx
  src/pages/pipeline-details/components/ReserveLogs/types.ts
  src/pages/pipeline-details/providers/DynamicData/types.ts
  src/pages/pipeline-details/providers/DynamicData/utils.ts
  src/pages/pipeline-details/view.tsx
Labels: enhancement, feature

#510 feat: Set ns from token, add avatar, add namespaces metric (#509)
  Dockerfile
  src/components/EmptyList/index.tsx
  src/components/EmptyList/types.ts
  src/k8s/groups/Capsule/Tenant/config.ts
  src/k8s/groups/Capsule/Tenant/index.ts
  src/k8s/groups/Capsule/Tenant/types.ts
  src/widgets/ResourceQuotas/components/RQItem/index.tsx
  src/widgets/ResourceQuotas/constants.ts
  src/widgets/ResourceQuotas/index.tsx
Labels: enhancement, feature

#512 feat: Add cdpipeline compact view mode
  src/icons/iconify-icons-mapping.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/types.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/styles.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/types.ts
  src/pages/cdpipeline-details/components/StageList/index.tsx
  src/pages/cdpipeline-details/components/StageListFilter/index.tsx
  src/pages/cdpipeline-details/page.tsx
  src/providers/ViewMode/provider.tsx
  src/providers/ViewMode/types.ts
Labels: feature

#516 fix: Try fix wrong success oidc auth
  Dockerfile
  src/pages/component-details/view.tsx
  src/pages/pipeline-details/view.tsx
Labels: bug

#517 fix: Try fix wrong success oidc auth
  Dockerfile
  src/pages/pipeline-details/view.tsx
Labels: bug

#518 fix: Try fix oidc fail token
  Dockerfile
Labels: bug

#522 chore: Update current development version (#521)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#525 feat: Add build with params
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/types.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx
Labels: enhancement, feature

#527 feat: Truncate pipelinerun names
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
  src/k8s/groups/default/ResourceQuota/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
  src/pages/pipeline-details/components/ReserveLogs/components/AllLogs/index.tsx
  src/utils/truncateName.ts
Labels: bug, enhancement

#531 fix: Bitbucket repo branch link (#530)
  src/services/link-creation/git/index.test.ts
  src/services/link-creation/git/index.ts
Labels: bug, enhancement

#533 feat: Update build git-source-url
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/Name/index.tsx
Labels: bug, enhancement
