Repository epam/edp-headlamp, pull requests merged in 2024-07, with the labels that each got.

#279 fix: Update codemie chat response
  src/widgets/AIChat/components/Chat/index.tsx
  src/widgets/AIChat/hooks/useStreaming.ts
  src/widgets/AIChat/index.tsx
  src/widgets/AIChat/types.ts
Labels: bug, enhancement

#281 feat: Update create/edit modals
  src/components/PageWrapper/index.tsx
  src/providers/Form/components/FormCheckbox/index.tsx
  src/widgets/CreateCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/CreateCodebaseBranch/components/DialogHeader/index.tsx
  src/widgets/CreateCodebaseBranch/components/FormActions/index.tsx
  src/widgets/CreateCodebaseFromTemplate/__snapshots__/index.test.tsx.snap
  src/widgets/CreateCodebaseFromTemplate/components/FormActions/index.tsx
  src/widgets/CreateCodebaseFromTemplate/components/Preview/index.tsx
  src/widgets/CreateCodebaseFromTemplate/index.tsx
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCDPipeline/components/Create/components/DialogHeader/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/Form/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/Form/types.ts
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/types.ts
  src/widgets/CreateEditCDPipeline/components/Create/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/styles.ts
  src/widgets/CreateEditCDPipeline/components/Edit/components/DialogHeader/index.tsx
  src/widgets/CreateEditCDPipeline/components/Edit/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/constants.ts
  src/widgets/CreateEditCDPipeline/names.ts
  src/widgets/CreateEditCodebase/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCodebase/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCodebase/components/Create/components/Selection/index.tsx
  src/widgets/CreateEditCodebase/components/Edit/components/DialogHeader/index.tsx
  src/widgets/CreateEditCodebase/components/Edit/components/FormActions/index.tsx
  src/widgets/CreateEditCodebase/constants.ts
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditStage/components/Create/components/DialogHeader/index.tsx
  src/widgets/CreateEditStage/components/Create/components/Form/index.tsx
  src/widgets/CreateEditStage/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditStage/components/Create/index.tsx
  src/widgets/CreateEditStage/components/Edit/components/DialogHeader/index.tsx
  src/widgets/CreateEditStage/components/Edit/components/FormActions/index.tsx
  src/widgets/CreateEditStage/components/fields/QualityGates/index.tsx
  src/widgets/CreateEditStage/constants.ts
  src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageQuickLink/components/Create/components/DialogHeader/index.tsx
  src/widgets/ManageQuickLink/components/Create/components/FormActions/index.tsx
  src/widgets/ManageQuickLink/components/Edit/components/DialogHeader/index.tsx
  src/widgets/ManageQuickLink/components/Edit/components/FormActions/index.tsx
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
Labels: enhancement, feature

#283 feat: Update environment creation
  assets/manifest.json
  src/components/EmptyList/index.tsx
  src/components/EmptyList/types.ts
  src/k8s/EDPCDPipeline/hooks/useCreateCDPipeline.ts
  src/pages/edp-cdpipeline-details/components/StageList/index.tsx
  src/pages/edp-cdpipeline-details/components/StageListFilter/index.tsx
  src/providers/Dialog/mapping.tsx
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/components/Create/components/Form/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/Form/types.ts
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/types.ts
  src/widgets/CreateEditCDPipeline/components/Create/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/PipelineName/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/PipelineName/types.ts
  src/widgets/CreateEditCDPipeline/components/fields/Stages/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/Stages/types.ts
  src/widgets/CreateEditCDPipeline/components/fields/index.ts
  src/widgets/CreateEditCDPipeline/constants.ts
  src/widgets/SuccessModal/constants.ts
  src/widgets/SuccessModal/index.tsx
  src/widgets/SuccessModal/types.ts
Labels: feature

#285 feat: Update apps field in env creation
  src/providers/Form/components/FormAutocomplete/index.tsx
  src/providers/Form/components/FormAutocomplete/types.ts
  src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx
  src/widgets/CreateEditCDPipeline/components/fields/Applications/index.tsx
Labels: enhancement

#289 chore: Update links to new documentation location (#288)
  README.md
  package-lock.json
  package.json
  src/constants/urls.ts
  src/widgets/CreateCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditCodebase/__snapshots__/index.edit.test.tsx.snap
  src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap
  src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap
  src/widgets/HelpMenu/menu.ts
Labels: documentation

#292 feat: Add err msg in create modal
  Dockerfile
Labels: enhancement, feature

#294 feat: Add permissions checks in cfg pages
  src/pages/edp-cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/edp-configuration/components/ConfigurationPageContent/index.tsx
  src/pages/edp-configuration/constants.ts
  src/pages/edp-configuration/pages/edp-argocd-integration/page.tsx
  src/pages/edp-configuration/pages/edp-cluster-list/page.tsx
  src/pages/edp-configuration/pages/edp-codemie-integration/page.tsx
  src/pages/edp-configuration/pages/edp-defect-dojo-integration/page.tsx
  src/pages/edp-configuration/pages/edp-dependency-track-integration/page.tsx
  src/pages/edp-configuration/pages/edp-gitops/page.tsx
  src/pages/edp-configuration/pages/edp-gitserver-list/page.tsx
  src/pages/edp-configuration/pages/edp-jira-integration/page.tsx
  src/pages/edp-configuration/pages/edp-nexus-integration/page.tsx
  src/pages/edp-configuration/pages/edp-registry-list/page.tsx
  src/pages/edp-configuration/pages/edp-sonar-integration/page.tsx
  src/pages/edp-configuration/pages/edp-sso-integration/page.tsx
  src/pages/edp-configuration/providers/Permissions/context.ts
  src/pages/edp-configuration/providers/Permissions/hooks.ts
  src/pages/edp-configuration/providers/Permissions/provider.tsx
  src/pages/edp-configuration/providers/Permissions/types.ts
  src/pages/edp-overview-list/components/ComponentList/components/AddNewQuickLinkCard/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
Labels: bug, enhancement

#296 feat: Update chat logic
  src/widgets/AIChat/components/Chat/index.tsx
  src/widgets/AIChat/components/ChatHistory/index.tsx
  src/widgets/AIChat/components/ChatHistory/types.ts
  src/widgets/AIChat/components/Message/styles.ts
  src/widgets/AIChat/hooks/useStreaming.ts
  src/widgets/AIChat/index.tsx
  src/widgets/AIChat/styles.ts
  src/widgets/AIChat/types.ts
  src/widgets/AIChat/utils.ts
Labels: enhancement

#299 fix: Fix issues after review
  Dockerfile
  src/pages/edp-configuration/pages/edp-gitops/constants.ts
  src/pages/edp-configuration/pages/edp-gitops/page.tsx
  src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/context.ts
  src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/hooks.ts
  src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/provider.tsx
  src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/types.ts
  src/pages/edp-configuration/pages/edp-gitops/view.tsx
  src/pages/edp-configuration/pages/edp-jira-integration/view.tsx
  src/widgets/ManageJiraServer/hooks/useJiraServerCreateForm.ts
  src/widgets/ManageJiraServer/hooks/useJiraServerEditForm.ts
  src/widgets/ManageJiraServer/index.tsx
Labels: bug

#300 fix: Fix issues after review
  src/pages/edp-cdpipeline-list/view.tsx
Labels: bug

#303 fix: Fix issues
  Dockerfile
  src/k8s/TaskRun/index.ts
  src/pages/edp-configuration/pages/edp-sso-integration/view.tsx
Labels: bug

#305 feat: Add pull request link
  src/k8s/PipelineRun/utils/getPullRequestURL/index.test.ts
  src/k8s/PipelineRun/utils/getPullRequestURL/index.ts
  src/pages/edp-cdpipeline-list/view.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: feature

#306 fix: Fix pipeline crash when no params
  src/k8s/PipelineRun/utils/getPullRequestURL/index.ts
Labels: bug

#308 chore: Replace hardcoded Keycloak URL prefix
  deploy-templates/README.md
  deploy-templates/templates/deployment.yaml
  deploy-templates/values.yaml
Labels: enhancement

#310 feat: Add query nav in pipeline page
  src/components/Graph/components/Node/index.tsx
  src/pages/edp-component-details/components/Pipeline/index.tsx
  src/pages/edp-configuration/providers/Permissions/context.ts
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/MenuAccordion/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/index.tsx
  src/pages/edp-pipeline-details/styles.ts
  src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx
  src/providers/Form/components/FormAutocomplete/types.ts
  src/widgets/CreateEditCDPipeline/components/Edit/index.tsx
  src/widgets/ManageJiraServer/components/JiraServer/fields/URL/index.tsx
  src/widgets/ManageJiraServer/components/JiraServer/fields/index.tsx
  src/widgets/PipelineRunGraph/hooks/useInfoRows.tsx
  src/widgets/PipelineRunGraph/index.tsx
Labels: enhancement, feature

#312 feat: Add ansible framework option
  src/configs/codebase-mappings/index.ts
  src/configs/codebase-mappings/library/index.ts
  src/configs/icon-mappings/index.ts
  src/icons/iconify-icons-mapping.ts
  src/icons/sprites/Resources/index.tsx
  src/icons/sprites/Resources/names.ts
  src/icons/sprites/Resources/symbols/Ansible.tsx
  src/icons/sprites/Resources/symbols/index.ts
  src/k8s/TaskRun/index.ts
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/MenuAccordion/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/hooks/useTabs.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageJiraServer/components/JiraServer/fields/URL/index.tsx
  src/widgets/ManageRegistry/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
Labels: bug, enhancement, feature
