Repository epam/edp-headlamp, pull requests merged in 2024-06, with the labels that each got.

#255 fix: Fix various ui ux issues (#254)
  Dockerfile
  src/pages/edp-component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/edp-component-details/components/Overview/index.tsx
  src/pages/edp-component-details/page.tsx
  src/pages/edp-component-details/providers/Data/provider.tsx
  src/pages/edp-component-details/view.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
  src/services/link-creation/sonar/index.test.ts
  src/services/link-creation/sonar/index.ts
  src/widgets/SonarQubeMetrics/index.tsx
  src/widgets/SonarQubeMetrics/types.ts
Labels: bug, enhancement, feature

#257 chore: Remove status field from route
  deploy-templates/templates/route.yaml
Labels: dependencies

#260 fix: Table layout fixes, fix ingress tooltip variable width (#258)
  src/components/Table/components/TableBody/components/TableRow/index.tsx
  src/components/Table/components/TableHead/components/TableRow/index.tsx
  src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx
Labels: bug, enhancement

#261 fix: App improvements and fixes
  src/components/InfoColumns/index.tsx
  src/pages/edp-stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx
  src/pages/edp-stage-details/components/Applications/components/ImageStreamTagsSelect/types.ts
  src/pages/edp-stage-details/components/Applications/hooks/useButtonsEnabled.ts
  src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/edp-stage-details/components/Applications/hooks/useConfigurationHandlers.ts
  src/pages/edp-stage-details/components/Applications/index.tsx
  src/pages/edp-stage-details/components/ApplicationsWrapper/index.tsx
  src/providers/Filter/components/Filter/index.tsx
  src/providers/Form/index.tsx
  src/widgets/CreateCodebaseFromTemplate/components/fields/GitUrlPath/index.tsx
  src/widgets/CreateEditCodebase/components/fields/GitUrlPath/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: bug, enhancement, feature

#262 fix: Fix filter fields alignment
  src/pages/edp-pipelines/components/PipelineRunList/index.tsx
Labels: bug

#264 chore: Update current development version
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#267 feat: Update pipeline page
  src/components/ActionsInlineList/index.tsx
  src/components/BorderedSection/index.tsx
  src/components/BorderedSection/types.ts
  src/components/QuickLink/index.tsx
  src/components/ResourceIconLink/index.tsx
  src/components/StatusIcon/types.ts
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/hooks/useInfoRows.tsx
  src/pages/edp-pipeline-details/components/PipelineRunDetails/index.tsx
  src/pages/edp-pipeline-details/styles.ts
  src/pages/edp-pipeline-details/view.tsx
  src/types/actions/index.ts
  src/utils/actions/createKubeAction/index.ts
  src/widgets/PipelineRunActionsMenu/index.tsx
Labels: enhancement
