Repository epam/edp-headlamp, pull requests merged in 2025-06, with the labels that each got.

#763 feat: Add branch selection (#762)
  src/providers/Form/components/FormAutocompleteSingle/index.tsx
  src/services/api/index.ts
  src/utils/getToken.ts
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/Owner/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/Repository/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchName/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/index.test.tsx
  src/widgets/dialogs/ManageCodebaseBranch/providers/CurrentDialog/provider.tsx
  src/widgets/dialogs/ManageCodebaseBranch/providers/CurrentDialog/types.ts
Labels: feature

#765 chore: Update codeql and codecov scan gh actions (#764)
  .github/workflows/codeql.yaml
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
Labels: enhancement

#767 fix: Improve deployment page features
  src/components/TooltipWithLinkList/index.tsx
  src/k8s/groups/EDP/QuickLink/constants.ts
  src/pages/stage-details/components/Applications/components/ValuesOverrideSwitch/index.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/components/Applications/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/providers/CurrentDialog/context.ts
Labels: bug, enhancement

#770 feat: Add base branch selection
  Dockerfile
  src/providers/Form/components/FormAutocompleteSingle/index.tsx
  src/providers/Form/components/FormAutocompleteSingle/types.ts
  src/providers/Form/components/FormSelect/index.tsx
  src/utils/getToken.ts
  src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageCodebaseBranch/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchName/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchVersion/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/names.ts
Labels: enhancement, feature

#772 chore: Update snapshot (#769)
  Dockerfile
Labels: enhancement, feature

#774 feat: Add pattern based icon mapping
  src/configs/icon-mappings/index.test.ts
  src/configs/icon-mappings/index.ts
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
  src/pages/component-list/components/ComponentList/hooks/useColumns.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplateCard/index.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/hooks/useColumns.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/FormDefaultValues/index.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/Preview/index.tsx
Labels: enhancement

#776 fix: Cluster integration page issues
  src/k8s/groups/default/Secret/utils/createClusterSecretInstance/index.test.ts
  src/k8s/groups/default/Secret/utils/createClusterSecretInstance/index.ts
  src/pages/configuration/pages/clusters/view.tsx
  src/providers/Form/components/FormRadioGroup/index.tsx
  src/providers/Form/components/FormRadioGroup/types.ts
  src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageClusterSecret/components/Create/components/Form/index.tsx
  src/widgets/ManageClusterSecret/components/Create/index.tsx
  src/widgets/ManageClusterSecret/components/Edit/components/Form/index.tsx
  src/widgets/ManageClusterSecret/components/Edit/hooks/useDefaultValues.ts
  src/widgets/ManageClusterSecret/components/fields/ClusterType/index.tsx
  src/widgets/ManageClusterSecret/utils.ts
Labels: bug, enhancement
