Repository epam/edp-headlamp, pull requests merged in 2025-03, with the labels that each got.

#655 feat: Add gitserver delete
  src/k8s/groups/EDP/Codebase/hooks/useCodebasesByGitServerLabelQuery.ts
  src/k8s/groups/EDP/Codebase/index.ts
  src/k8s/groups/EDP/Codebase/labels.ts
  src/k8s/groups/EDP/Codebase/requestKeys.ts
  src/k8s/groups/EDP/Codebase/utils/createCodebaseInstance/index.ts
  src/pages/configuration/pages/gitservers/constants.ts
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitServer/components/Actions/index.tsx
  src/widgets/ManageGitServer/components/DeletionDialog/index.tsx
  src/widgets/ManageGitServer/components/DeletionDialog/types.ts
  src/widgets/ManageGitServer/constants.ts
  src/widgets/ManageGitServer/index.create.test.tsx
  src/widgets/ManageGitServer/index.edit.test.tsx
  src/widgets/ManageGitServer/providers/Data/context.ts
  src/widgets/ManageGitServer/providers/Data/index.tsx
  src/widgets/ManageGitServer/providers/Data/types.ts
Labels: feature

#659 fix: Select all btn state
  Dockerfile
  src/components/Table/components/TableHead/components/TableRow/index.tsx
Labels: bug

#671 chore: Align base headlamp image version
  Dockerfile
Labels: enhancement

#672 feat: Update kubecfg preview
  Dockerfile
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/CodebaseVersioning/index.tsx
Labels: enhancement

#675 fix: Edp config query
  Dockerfile
  src/k8s/groups/default/ConfigMap/constants.ts
  src/k8s/groups/default/ConfigMap/hooks/useEDPConfigMap.ts
  src/k8s/groups/default/ConfigMap/index.ts
  src/pages/component-details/providers/Data/provider.tsx
  src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx
  src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx
  src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx
  src/widgets/dialogs/ManageVCluster/providers/CurrentDialog/provider.tsx
Labels: bug, enhancement, tech debt

#677 feat: Add codebase field private
  src/providers/Form/components/FormCheckbox/index.tsx
  src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/Form/index.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/Private/index.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/index.ts
  src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts
  src/widgets/dialogs/CreateCodebaseFromTemplate/names.ts
  src/widgets/dialogs/ManageCodebase/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/index.tsx
  src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebase/components/fields/Private/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/index.ts
  src/widgets/dialogs/ManageCodebase/names.ts
  src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageQuickLink/__snapshots__/index.test.tsx.snap
Labels: enhancement, feature

#679 feat: Add run from triggertemplate
  src/k8s/groups/Tekton/Pipeline/labels.ts
  src/pages/pipelines/components/index.tsx
  src/pages/pipelines/pages/pipeline-details/components/Overview/index.tsx
  src/pages/pipelines/pages/pipeline-details/view.tsx
  src/pages/pipelines/pages/pipeline-list/view.tsx
  src/widgets/PipelineActionsMenu/index.tsx
  src/widgets/PipelineActionsMenu/types.ts
  src/widgets/PipelineList/components/Actions/index.tsx
  src/widgets/PipelineList/hooks/useColumns.tsx
  src/widgets/PipelineList/index.tsx
  src/widgets/PipelineList/types.ts
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx
Labels: enhancement

#681 fix: Codebase validation tab change
  src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.ts
  src/widgets/PipelineActionsMenu/index.tsx
  src/widgets/dialogs/ManageCodebase/names.ts
Labels: bug

#684 fix: No tasks/taskruns loading state
  src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.ts
  src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
  src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx
  src/pages/pipelines/pages/pipeline-run-details/view.tsx
  src/widgets/PipelineRunGraph/index.tsx
Labels: bug

#687 feat: Add cluster secret status
  src/k8s/groups/default/Secret/annotations.ts
  src/pages/configuration/pages/clusters/view.tsx
Labels: enhancement

#689 chore: Update current development version (#688)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#694 chore: Update image
  Dockerfile
Labels: dependencies

#695 fix: Sonar error
  src/widgets/LogViewer/index.tsx
Labels: routine

#696 chore: Update image version
  Dockerfile
Labels: routine

#700 chore: Update current development version (#699)
  CHANGELOG.md
  deploy-templates/Chart.yaml
Labels: enhancement

#701 fix: Pipelinerun page conditional rendering
  src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
  src/pages/pipelines/pages/pipeline-run-details/components/ReserveLogs/hooks/useTabs.tsx
  src/pages/pipelines/pages/pipeline-run-details/hooks/useTabs.tsx
  src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx
  src/pages/pipelines/pages/pipeline-run-details/view.tsx
Labels: bug

#702 chore: Update current development version (#699)
  CHANGELOG.md
  deploy-templates/Chart.yaml
Labels: enhancement
