Repository epam/edp-headlamp, pull requests merged in 2025-02, with the labels that each got.

#585 feat: Add java21
  src/configs/codebase-mappings/application/index.ts
  src/configs/codebase-mappings/autotest/index.ts
  src/configs/codebase-mappings/index.ts
  src/configs/codebase-mappings/library/index.ts
  src/configs/icon-mappings/index.ts
Labels: enhancement

#587 fix: Rerun and argocd status color
  src/constants/colors.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
Labels: bug

#589 fix: Applications deploy render (#588)
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/components/ApplicationsWrapper/index.tsx
Labels: bug

#591 feat: Add cdpipeline description edit
  src/components/Table/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/Edit/components/Form/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts
Labels: enhancement

#597 feat: Update cdpipeline delete noty
  src/k8s/common/hooks/useDeleteKubeObject/index.ts
  src/k8s/common/hooks/useDeleteKubeObject/index.tsx
  src/k8s/groups/EDP/CDPipeline/hooks/useCDPIpelineCRUD.ts
  src/widgets/CDPipelineActionsMenu/index.tsx
  src/widgets/dialogs/DeleteKubeObject/index.tsx
  src/widgets/dialogs/DeleteKubeObject/types.ts
  src/widgets/dialogs/ManageCDPipeline/components/Create/components/FormActions/index.tsx
Labels: enhancement

#593 feat: Add ingresses in stage app
  src/components/TooltipWithLinkList/index.tsx
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
Labels: enhancement

#599 feat: Add copy button
  src/components/CopyButton/index.tsx
  src/components/Section/index.tsx
  src/components/Section/types.ts
  src/icons/iconify-icons-mapping.ts
  src/pages/cdpipeline-details/view.tsx
  src/pages/component-details/view.tsx
  src/pages/configuration/pages/pipeline-details/view.tsx
  src/pages/configuration/pages/task-details/view.tsx
  src/pages/pipeline-details/view.tsx
  src/pages/stage-details/view.tsx
Labels: feature

#601 fix: CDpipeline message pr lint
  src/pages/component-list/components/ComponentList/components/ComponentMultiDeletion/index.tsx
  src/widgets/ManageJiraServer/hooks/useResetIntegration.ts
Labels: bug

#602 feat: Move ingress button (#592)
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
Labels: bug

#604 feat: Add xterm link addon
  Dockerfile
  package-lock.json
  package.json
  src/components/LogViewer/index.tsx
  src/components/Table/components/TableBody/index.tsx
  src/components/Table/components/TableHead/components/TableRow/index.tsx
  src/components/Table/components/TableSettings/index.tsx
  src/components/Table/index.tsx
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
Labels: enhancement

#605 fix: Add copy button to branch name and vcs tag (#598)
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: enhancement

#607 feat: Add protected check and refactor actions (#606)
  src/constants/resourceActions.ts
  src/k8s/common/labels.ts
  src/utils/actions/createKubeAction/index.ts
  src/utils/actions/createResourceAction/index.test.ts
  src/utils/actions/createResourceAction/index.ts
  src/widgets/CDPipelineActionsMenu/index.tsx
  src/widgets/CodebaseActionsMenu/index.tsx
  src/widgets/CodebaseBranchActionsMenu/index.tsx
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/QuickLinkActionsMenu/index.tsx
  src/widgets/StageActionsMenu/index.tsx
  src/widgets/StageActionsMenu/utils.ts
Labels: enhancement

#609 fix: Pipeline page router history change
  src/pages/pipeline-details/components/Details/index.tsx
Labels: bug

#612 fix: Values override value
  src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
Labels: bug

#614 feat: Add table columns resize
  src/components/Table/components/TableHead/components/TableRow/index.tsx
  src/components/Table/components/TableHead/components/TableRow/types.ts
  src/components/Table/components/TableHead/index.tsx
  src/components/Table/components/TableHead/types.ts
  src/components/Table/components/TableSettings/index.tsx
  src/components/Table/components/TableSettings/utils.ts
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
  src/pages/component-list/components/ComponentList/hooks/useColumns.tsx
  src/pages/configuration/pages/quicklinks/components/ComponentList/hooks/useColumns.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/hooks/useColumns.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/widgets/PipelineList/hooks/useColumns.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/TaskList/hooks/useColumns.tsx
Labels: enhancement

#616 fix: Pagination and topbar items
  Dockerfile
  src/components/PageLogicWrapper/index.tsx
  src/components/Table/components/TablePagination/index.tsx
  src/components/Table/constants.ts
  src/index.tsx
  src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx
  src/providers/Filter/components/Filter/index.tsx
  src/widgets/AIChat/index.tsx
  src/widgets/AIChat/utils.ts
  src/widgets/ResourceQuotas/index.tsx
Labels: bug, enhancement

#618 fix: CDPipeline create validation
  src/widgets/dialogs/ManageCDPipeline/components/Create/components/FormActions/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
Labels: bug

#620 feat: Unhide pipeline columns for gitops
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
Labels: enhancement

#624 fix: Component page crash
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
  src/pages/component-details/providers/DynamicData/provider.tsx
  src/pages/component-list/components/ComponentList/index.tsx
  src/pages/stage-details/hooks/useInfoColumns.tsx
  src/widgets/Pipeline/index.tsx
  src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebase/types.ts
Labels: bug

#626 fix: Root page token expire state
  Dockerfile
Labels: bug

#628 fix: Pipeline list infinite load
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
Labels: bug

#630 fix: Terminal pod change
  src/widgets/dialogs/PodsTerminal/index.tsx
Labels: bug

#632 fix: Fix Deployment manifest generation issue (#631)
  deploy-templates/templates/deployment.yaml
Labels: enhancement

#639 fix: Text with tooltip
  src/components/TextWithTooltip/index.tsx
  src/pages/cdpipeline-details/components/StageList/index.tsx
Labels: bug

#642 fix: Cluster name value irsa
  src/widgets/ManageClusterSecret/components/Edit/hooks/useDefaultValues.ts
Labels: bug

#643 fix: Root page token expire
  Dockerfile
  src/pages/overview-list/route.tsx
  src/routes/sidebar-list.ts
Labels: bug

#645 feat: Update edit protection
  src/k8s/common/labels.ts
  src/utils/actions/createResourceAction/index.test.ts
  src/utils/actions/createResourceAction/index.ts
Labels: enhancement

#649 feat: Add filter by app in dflow list
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useFilter.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/types.ts
  src/pages/cdpipeline-list/constants.ts
  src/pages/cdpipeline-list/page.tsx
  src/pages/cdpipeline-list/types.ts
  src/pages/cdpipeline-list/view.tsx
Labels: enhancement

#651 feat: Update edp versioning name (#650)
  src/configs/select-options/codebaseVersioningTypes.ts
  src/constants/codebaseVersioningTypes.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
  src/widgets/ManageGitOps/hooks/useDefaultValues.ts
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/Form/hooks/useUpdateVersioningFields.ts
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/CodebaseVersioning/index.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/hooks/useUpdateVersioningFields.ts
  src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts
  src/widgets/dialogs/ManageCodebase/components/fields/CodebaseVersioning/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/components/Create/components/Form/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/components/Create/hooks/useDefaultValues.ts
Labels: enhancement

#653 feat: Disable monitoring button for non grafana providers
  src/pages/stage-details/hooks/usePageTabs.tsx
Labels: enhancement
