Repository epam/edp-headlamp, pull requests merged in 2025-07, with the labels that each got.

#786 fix: Pipelinerun page with no available api url (#784)
  src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
  src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx
  src/pages/pipelines/pages/pipeline-run-details/view.tsx
Labels: bug

#787 fix: Pipelinerun page white if no approval tasks
  src/k8s/groups/Tekton/PipelineRun/hooks/usePipelineRunData.ts
  src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
Labels: bug

#788 fix: Pipelinerun page white if no approval tasks
  src/k8s/groups/Tekton/PipelineRun/hooks/usePipelineRunData.ts
  src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
Labels: bug

#793 fix: Query for pipelineruns history
  src/pages/pipelines/pages/pipeline-run-history-list/logs.query.ts
Labels: bug

#794 fix: Issues for release 0.23
  src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx
  src/providers/MultiForm/context.ts
  src/providers/MultiForm/provider.tsx
  src/providers/MultiForm/types.ts
  src/widgets/ManageRegistry/components/Actions/index.tsx
  src/widgets/ManageRegistry/hooks/useSharedForm.ts
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Labels: bug

#795 fix: Cover no apibaseurl case for codebases onboarding
  src/services/api/index.ts
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/Owner/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/Repository/index.tsx
Labels: bug, enhancement

#797 fix: Fromcommit field free solo mode (#791)
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Labels: bug

#799 chore: Update current development version (#798)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#803 fix: Branch dialog discovery errors
  src/widgets/dialogs/ManageCodebase/components/fields/Owner/index.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/Repository/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchName/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Labels: bug
