Repository epam/edp-headlamp, pull requests merged in 2025-04, with the labels that each got.

#705 feat: Add new docs links, update others
  src/constants/urls.ts
  src/pages/cdpipeline-details/view.tsx
  src/pages/component-details/components/Overview/index.tsx
  src/pages/component-details/view.tsx
  src/pages/configuration/pages/clusters/constants.ts
  src/pages/configuration/pages/gitservers/constants.ts
  src/pages/configuration/pages/quicklinks/constants.ts
  src/pages/marketplace/view.tsx
  src/pages/overview-list/view.tsx
  src/pages/pipelines/pages/pipeline-list/constants.ts
  src/pages/pipelines/pages/pipeline-run-list/constants.ts
  src/pages/pipelines/pages/task-list/constants.ts
  src/pages/stage-details/view.tsx
  src/widgets/dialogs/CreateCodebaseFromTemplate/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/CreateCodebaseFromTemplate/components/Preview/index.tsx
Labels: enhancement

#707 fix: Pipelinerun create from pipeline
  src/widgets/PipelineActionsMenu/index.tsx
Labels: bug

#708 fix: Kubecfg show on first try
  Dockerfile
Labels: bug

#710 feat: Add ability to add custom widgets
  src/components/RefPortal/index.tsx
  src/components/Table/components/TableBody/components/TableRow/index.tsx
  src/components/Table/components/TableBody/components/TableRow/types.ts
  src/components/Table/components/TableBody/index.tsx
  src/components/Table/components/TableBody/types.ts
  src/components/Table/components/TableHead/index.tsx
  src/components/Table/components/TableHead/types.ts
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/components/TileChart/styles.ts
  src/pages/component-list/components/ComponentActions/index.tsx
  src/pages/overview-list/components/AddNewWidget/index.tsx
  src/pages/overview-list/components/AddNewWidget/styles.ts
  src/pages/overview-list/components/UserWidgetsRenderer/index.tsx
  src/pages/overview-list/page.tsx
  src/pages/overview-list/providers/UserWidgets/index.tsx
  src/pages/overview-list/view.tsx
  src/widgets/AppVersion/hooks/useColumns.tsx
  src/widgets/AppVersion/index.tsx
  src/widgets/dialogs/AddNewWidget/components/DialogInner/Configuration/index.tsx
  src/widgets/dialogs/AddNewWidget/components/DialogInner/Selection/index.tsx
  src/widgets/dialogs/AddNewWidget/components/DialogInner/index.tsx
  src/widgets/dialogs/AddNewWidget/constants.ts
  src/widgets/dialogs/AddNewWidget/forms/AppVersionWidgetForm/index.tsx
  src/widgets/dialogs/AddNewWidget/index.tsx
  src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/context.ts
  src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/hooks.ts
  src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/provider.tsx
  src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/types.ts
  src/widgets/dialogs/AddNewWidget/types.ts
Labels: feature

#711 fix: Autocomplete numtag spacing
  Dockerfile
  src/providers/Form/components/FormAutocomplete/index.tsx
Labels: bug

#715 fix: Integration create popup actions
  src/widgets/ManageArgoCD/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageArgoCD/components/Actions/index.tsx
  src/widgets/ManageChatAssistant/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageChatAssistant/components/Actions/index.tsx
  src/widgets/ManageDefectDojo/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDefectDojo/components/Actions/index.tsx
  src/widgets/ManageDependencyTrack/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageDependencyTrack/components/Actions/index.tsx
  src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitServer/components/Actions/index.tsx
  src/widgets/ManageGitServer/index.tsx
  src/widgets/ManageGitServer/providers/Data/types.ts
  src/widgets/ManageJiraServer/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageJiraServer/components/Actions/index.tsx
  src/widgets/ManageJiraServer/index.tsx
  src/widgets/ManageNexus/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageNexus/components/Actions/index.tsx
  src/widgets/ManageRegistry/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageRegistry/components/Actions/index.tsx
  src/widgets/ManageSonar/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageSonar/components/Actions/index.tsx
Labels: bug

#717 fix: Gitserver create cancel btn
  src/widgets/ManageGitServer/providers/Data/context.ts
  src/widgets/ManageGitServer/providers/Data/index.tsx
Labels: bug

#719 fix: Filter search function
  src/providers/Filter/constants.ts
Labels: bug

#722 fix: Prod source maps
  Dockerfile
  package.json
  src/widgets/PipelineActionsMenu/index.tsx
Labels: dependencies

#726 chore: Update current development version (#725)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#731 feat: Add copy deployed versions btn
  src/components/CopyButton/index.tsx
  src/components/Section/index.tsx
  src/pages/stage-details/components/Applications/hooks/useColumns.tsx
  src/pages/stage-details/components/Applications/index.tsx
  src/providers/Form/components/FormAutocomplete/index.tsx
  src/providers/Form/components/FormAutocompleteSingle/index.tsx
  src/providers/Form/components/FormControlLabelWithTooltip/index.tsx
  src/providers/Form/components/FormTextField/index.tsx
  src/providers/Form/components/FormTextFieldEditable/index.tsx
  src/providers/Form/components/FormTextFieldEncoded/index.tsx
  src/providers/Form/components/FormTextFieldPassword/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
  src/widgets/dialogs/ManageStage/components/fields/QualityGates/index.tsx
Labels: feature

#736 chore: Bump GitHub Actions runner image to 22.04(#735)
  .github/workflows/pr.yaml
Labels: enhancement

#733 feat: Update branch name validation
  src/k8s/groups/Capsule/Tenant/schema.ts
  src/k8s/groups/Capsule/Tenant/types.ts
  src/k8s/groups/EDP/Codebase/hooks/useEnrichedApplicationsWithImageStreamsQuery.ts
  src/k8s/groups/EDP/CodebaseBranch/utils/createCodebaseBranchInstance/index.test.ts
  src/k8s/groups/EDP/CodebaseBranch/utils/createCodebaseBranchInstance/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Actions/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/TableHeaderActions/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/index.tsx
  src/widgets/CodebaseBranchActionsMenu/index.tsx
  src/widgets/CodebaseBranchActionsMenu/types.ts
  src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchName/index.tsx
  src/widgets/dialogs/ManageCodebaseBranch/index.test.tsx
  src/widgets/dialogs/ManageCodebaseBranch/providers/CurrentDialog/context.ts
  src/widgets/dialogs/ManageCodebaseBranch/types.ts
Labels: enhancement, feature

#739 fix: Pipeline page filter context
  src/pages/pipelines/pages/pipeline-details/page.tsx
Labels: bug

#741 feat: Add pipeline history
  src/pages/pipelines/components/index.tsx
  src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/logs.query.ts
  src/pages/pipelines/pages/pipeline-run-history-list/constants.ts
  src/pages/pipelines/pages/pipeline-run-history-list/hooks/useColumns.tsx
  src/pages/pipelines/pages/pipeline-run-history-list/logs.query.ts
  src/pages/pipelines/pages/pipeline-run-history-list/page.tsx
  src/pages/pipelines/pages/pipeline-run-history-list/route.tsx
  src/pages/pipelines/pages/pipeline-run-history-list/types.ts
  src/pages/pipelines/pages/pipeline-run-history-list/utils.ts
  src/pages/pipelines/pages/pipeline-run-history-list/view.tsx
  src/routes/index.tsx
Labels: feature

#744 fix: Filter by label function in search (#743)
  src/providers/Filter/constants.ts
Labels: bug

#749 fix: Filter issues
  src/components/DataGrid/index.tsx
  src/components/EmptyList/index.tsx
  src/components/Section/index.tsx
  src/pages/cdpipeline-details/components/StageList/index.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx
  src/pages/stage-details/hooks/useInfoColumns.tsx
  src/providers/Filter/components/Filter/index.tsx
  src/widgets/PipelineList/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/PipelineRunList/hooks/useFilter.tsx
  src/widgets/PipelineRunList/index.tsx
  src/widgets/TaskList/index.tsx
Labels: bug
