Repository epam/edp-headlamp, pull requests merged in 2025-01, with the labels that each got.

#535 feat: Make abstract quick links
  src/components/QuickLink/index.tsx
  src/components/QuickLink/types.ts
  src/components/ResourceIconLink/index.tsx
  src/components/ResourceIconLink/types.ts
  src/icons/iconify-icons-mapping.ts
  src/k8s/groups/EDP/QuickLink/constants.ts
  src/k8s/groups/EDP/QuickLink/labels.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/pages/configuration/pages/clusters/view.tsx
  src/pages/stage-details/components/Monitoring/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/view.tsx
  src/services/link-creation/grafana/index.test.ts
  src/services/link-creation/grafana/index.ts
  src/services/link-creation/index.ts
  src/services/link-creation/kibana/index.test.ts
  src/services/link-creation/kibana/index.ts
  src/services/link-creation/logging/index.test.ts
  src/services/link-creation/logging/index.ts
  src/services/link-creation/monitoring/index.test.ts
  src/services/link-creation/monitoring/index.ts
  src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageClusterSecret/components/Edit/components/FormActions/index.tsx
  src/widgets/ManageClusterSecret/components/fields/ClusterCertificate/index.tsx
  src/widgets/ManageClusterSecret/components/fields/ClusterHost/index.tsx
  src/widgets/ManageClusterSecret/components/fields/ClusterName/index.tsx
  src/widgets/ManageClusterSecret/components/fields/ClusterToken/index.tsx
  src/widgets/ManageClusterSecret/components/fields/SkipTLSVerify/index.tsx
  src/widgets/ManageClusterSecret/index.create.test.tsx
  src/widgets/ManageClusterSecret/index.edit.test.tsx
  src/widgets/ManageClusterSecret/index.tsx
  src/widgets/ManageClusterSecret/types.ts
Labels: enhancement, feature

#536 feat: Improve monitoring links
  src/k8s/groups/EDP/QuickLink/constants.ts
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/pages/stage-details/components/Monitoring/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/view.tsx
  src/services/link-creation/monitoring/index.test.ts
  src/services/link-creation/monitoring/index.ts
Labels: enhancement

#538 fix: Codemie loading, available clusters list
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/codemie/providers/DynamicData/types.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx
Labels: bug, enhancement

#539 fix: Codemie loading, monitoring url, deptrack url
  src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx
  src/pages/component-details/providers/Data/provider.tsx
  src/pages/component-details/providers/Data/types.ts
  src/pages/configuration/pages/codemie/view.tsx
  src/pages/configuration/pages/gitops/view.tsx
  src/pages/stage-details/components/Monitoring/index.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/pages/stage-details/view.tsx
  src/services/link-creation/deptrack/index.test.ts
  src/services/link-creation/deptrack/index.ts
  src/services/link-creation/logging/index.test.ts
  src/services/link-creation/logging/index.ts
  src/services/link-creation/monitoring/index.test.ts
  src/services/link-creation/monitoring/index.ts
  src/widgets/DeeptrackVulnerabilities/index.tsx
  src/widgets/DeeptrackVulnerabilities/types.ts
Labels: bug, enhancement

#541 feat: Update alert noty
  Dockerfile
  src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx
Labels: enhancement

#543 chore: Update current development version (#542)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#545 feat: Update pipelinerun naming
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.test.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts
  src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
  src/widgets/dialogs/ManageCodebase/components/fields/GitUrlPath/index.tsx
Labels: enhancement

#547 fix: Wrong loading state with no permissions
  src/pages/cdpipeline-list/components/CDPipelineList/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Details/index.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Details/types.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
  src/pages/component-list/components/ComponentList/index.tsx
  src/pages/configuration/pages/pipeline-list/view.tsx
  src/pages/configuration/pages/quicklinks/components/ComponentList/index.tsx
  src/pages/configuration/pages/task-list/view.tsx
  src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/index.tsx
  src/pages/marketplace/components/MarketplaceList/index.tsx
  src/pages/pipelines/view.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
Labels: bug

#549 refactor: Codemie page
  src/components/ErrorContent/index.tsx
  src/constants/urls.ts
  src/pages/configuration/pages/codemie/components/Applications/index.tsx
  src/pages/configuration/pages/codemie/components/Codemie/index.tsx
  src/pages/configuration/pages/codemie/components/CodemieProjectSettings/index.tsx
  src/pages/configuration/pages/codemie/constants.ts
  src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx
  src/pages/configuration/pages/codemie/view.tsx
Labels: enhancement

#551 feat: Update filter
  src/hooks/useResourceRequestStatusMessages/index.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.tsx
  src/k8s/groups/Tekton/PipelineRun/hooks/useCreateDeployPipelineRun.tsx
  src/pages/cdpipeline-details/components/StageListFilter/index.tsx
  src/pages/cdpipeline-details/constants.ts
  src/pages/cdpipeline-details/hooks/usePageFilterContext.ts
  src/pages/cdpipeline-details/types.ts
  src/pages/cdpipeline-list/view.tsx
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Details/index.tsx
  src/pages/component-list/components/ComponentListFilter/index.tsx
  src/pages/component-list/constants.ts
  src/pages/component-list/hooks/usePageFilterContext.ts
  src/pages/component-list/types.ts
  src/pages/configuration/pages/quicklinks/view.tsx
  src/pages/marketplace/view.tsx
  src/pages/stage-details/hooks/usePageTabs.tsx
  src/providers/Filter/components/Filter/index.tsx
  src/providers/Filter/components/Filter/types.ts
  src/providers/Filter/constants.ts
  src/providers/Filter/hooks.ts
  src/providers/Filter/provider.tsx
  src/providers/Filter/types.ts
  src/services/link-creation/deptrack/index.test.ts
  src/widgets/PipelineList/index.tsx
  src/widgets/PipelineRunActionsMenu/index.tsx
  src/widgets/PipelineRunList/constants.ts
  src/widgets/PipelineRunList/index.tsx
  src/widgets/PipelineRunList/types.ts
  src/widgets/TaskList/index.tsx
Labels: enhancement

#554 feat: Add CDPipeline description filed
  src/components/ResponsiveChips/index.tsx
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
  src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/dialogs/ManageCDPipeline/__snapshots__/index.test.tsx.snap
  src/widgets/dialogs/ManageCDPipeline/components/Create/components/Form/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/Description/index.tsx
  src/widgets/dialogs/ManageCDPipeline/components/fields/index.ts
  src/widgets/dialogs/ManageCDPipeline/names.ts
Labels: enhancement, feature

#555 fix: Undefined description crash
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
Labels: bug

#556 fix: No labels crash
  src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
  src/providers/Filter/constants.ts
  src/widgets/PipelineList/hooks/useColumns.tsx
  src/widgets/TaskList/hooks/useColumns.tsx
Labels: bug

#558 feat: Add results column into pipeline table
  src/components/InfoColumns/index.tsx
  src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts
  src/pages/component-details/providers/DynamicData/provider.tsx
  src/pages/pipeline-details/components/Overview/hooks/useInfoRows.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/PipelineRunResults/index.tsx
Labels: enhancement, feature

#563 feat: Add pr link, upd result column, upd gitops name
  src/icons/iconify-icons-mapping.ts
  src/k8s/groups/Tekton/PipelineRun/utils/getPullRequestURL/index.ts
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/index.tsx
  src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx
  src/pages/pipeline-details/view.tsx
  src/services/link-creation/git/index.test.ts
  src/widgets/ManageGitOps/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitOps/__snapshots__/index.edit.test.tsx.snap
  src/widgets/ManageGitOps/constants.ts
  src/widgets/ManageGitOps/index.edit.test.tsx
  src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx
  src/widgets/PipelineRunList/hooks/useColumns.tsx
  src/widgets/PipelineRunList/hooks/useUpperColumns.tsx
Labels: bug, enhancement, feature

#567 feat: Add import strategy for gitops create
  src/pages/component-details/providers/Data/provider.tsx
  src/widgets/ManageGitOps/__snapshots__/index.create.test.tsx.snap
  src/widgets/ManageGitOps/components/Create/index.tsx
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/hooks/useCodebaseCreationStrategies.tsx
  src/widgets/dialogs/ManageCodebase/components/fields/EmptyProject/index.tsx
Labels: enhancement

#569 fix: Clone codebase validation
  src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/FormActions/index.tsx
Labels: bug

#571 feat: Move pipeline results to separate tab
  src/pages/pipeline-details/components/Overview/hooks/useInfoRows.tsx
  src/pages/pipeline-details/hooks/useTabs.tsx
Labels: enhancement

#572 feat: Set ns from config
  Dockerfile
Labels: enhancement

#574 chore: Update current development version (#573)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  package-lock.json
  package.json
Labels: enhancement

#576 fix: Pr link button
  src/widgets/PipelineRunList/hooks/useColumns.tsx
Labels: bug

#580 feat: Remove remember settings check
  src/components/Table/components/TableSettings/index.tsx
  src/components/Table/components/TableSettings/types.ts
  src/components/Table/constants.ts
  src/components/Table/index.tsx
  src/components/Table/types.ts
Labels: enhancement

#582 fix: PipelineRuns request in branch
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
Labels: bug

#583 fix: Latest build pipeline run progress
  src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
Labels: bug
